// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpawgiscxsbbvxrjxjbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwYXdnaXNjeHNiYnZ4cmp4amJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwODMxODYsImV4cCI6MjA1MTY1OTE4Nn0.nkhkhvwWlj22oKdQ9tIBQaX2SekxJYrawRoJOb8bHPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);